import type { membershipRoleEnum } from "@/db/schema";

/** Mirrors the `membership_role` Postgres enum in src/db/schema.ts. */
export type MembershipRole = (typeof membershipRoleEnum.enumValues)[number];

export const PERMISSIONS = [
  "organization:manage",
  "membership:manage",
  "account:read",
  "account:manage",
  "fiscal_period:manage",
  "journal:read",
  "journal:post",
  "journal:reverse",
  "contact:read",
  "contact:manage",
  "tax_code:manage",
  "dimension:read",
  "dimension:manage",
  "audit:read",
  "bank_account:read",
  "bank_account:manage",
  "bank_transaction:import",
  "bank_transaction:reconcile",
  "bank_rule:manage",
  "customer_invoice:read",
  "customer_invoice:manage",
  "customer_invoice:post",
  "customer_invoice:void",
  "customer_payment:read",
  "customer_payment:manage",
  "customer_quote:read",
  "customer_quote:manage",
  "recurring_invoice:read",
  "recurring_invoice:manage",
  "supplier_bill:read",
  "supplier_bill:manage",
  "supplier_bill:post",
  "supplier_bill:void",
  "supplier_payment:read",
  "supplier_payment:manage",
  "onboarding:manage",
  "bank_transaction:ai_suggest",
  "expense_claim:read",
  "expense_claim:manage",
  "expense_claim:approve",
  "expense_receipt:manage",
  "purchase_order:read",
  "purchase_order:manage",
  "recurring_bill:read",
  "recurring_bill:manage",
  "supplier_credit:read",
  "supplier_credit:manage",
  "supplier_credit:post",
  "supplier_credit:void",
  "payment_run:read",
  "payment_run:manage",
  "payment_run:approve",
  "financial_report:read",
  "saved_report:manage",
  "project:read",
  "project:manage",
  "timesheet:read",
  "timesheet:manage",
  "timesheet:approve",
  "product:read",
  "product:manage",
  "inventory:read",
  "inventory:manage",
  "fixed_asset:read",
  "fixed_asset:manage",
  "employee:read",
  "employee:manage",
  "payrun:read",
  "payrun:manage",
  "payrun:post",
  "budget:read",
  "budget:manage",
  "forecast:read",
  "forecast:manage",
  "scenario:read",
  "scenario:manage",
  // Phase 9 Slice 3 (month-end close + period locking, master spec §40/§41).
  // `period:close` raises a period's lock level (and closes it);
  // `period:reopen` lowers a SOFT/ADVISOR lock; `period:reopen_hard` is the
  // most restricted — only it can lower a TAX_LOCKED/HARD_LOCKED period.
  // `period:override_soft` lets a holder post into a SOFT_LOCKED period with
  // an audited reason; `period:post_advisor_locked` lets the accountant keep
  // posting adjustments into an ADVISOR_LOCKED one. None of these is
  // reachable by any AI path (fiscal period close is a permanently
  // human-gated critical action — docs/ai-agents.md).
  "period:close",
  "period:reopen",
  "period:reopen_hard",
  "period:override_soft",
  "period:post_advisor_locked",
  "close_checklist:read",
  "close_checklist:manage",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

const ALL_PERMISSIONS = new Set<Permission>(PERMISSIONS);

/**
 * Static role → permission matrix for Phase 1. Later phases may extend this
 * with per-organization overrides (master spec §46's "attribute-level
 * policy enforcement"); a static matrix is the right amount of complexity
 * while the only permission-checked resources are the ledger, contacts, and
 * membership management.
 */
export const ROLE_PERMISSIONS: Record<MembershipRole, ReadonlySet<Permission>> = {
  OWNER: ALL_PERMISSIONS,
  ADMINISTRATOR: ALL_PERMISSIONS,
  ACCOUNTANT: new Set<Permission>([
    "account:read",
    "account:manage",
    "fiscal_period:manage",
    "journal:read",
    "journal:post",
    "journal:reverse",
    "financial_report:read",
    "saved_report:manage",
    "contact:read",
    "contact:manage",
    "tax_code:manage",
    "dimension:read",
    "dimension:manage",
    "audit:read",
    "bank_account:read",
    "bank_account:manage",
    "bank_transaction:import",
    "bank_transaction:reconcile",
    "bank_rule:manage",
    "customer_invoice:read",
    "customer_invoice:manage",
    "customer_invoice:post",
    "customer_invoice:void",
    "customer_payment:read",
    "customer_payment:manage",
    "customer_quote:read",
    "customer_quote:manage",
    "recurring_invoice:read",
    "recurring_invoice:manage",
    "supplier_bill:read",
    "supplier_bill:manage",
    "supplier_bill:post",
    "supplier_bill:void",
    "supplier_payment:read",
    "supplier_payment:manage",
    "bank_transaction:ai_suggest",
    "expense_claim:read",
    "expense_claim:manage",
    "expense_claim:approve",
    "expense_receipt:manage",
    "purchase_order:read",
    "purchase_order:manage",
    "recurring_bill:read",
    "recurring_bill:manage",
    "supplier_credit:read",
    "supplier_credit:manage",
    "supplier_credit:post",
    "supplier_credit:void",
    "payment_run:read",
    "payment_run:manage",
    "payment_run:approve",
    "project:read",
    "project:manage",
    "timesheet:read",
    "timesheet:manage",
    "timesheet:approve",
    "product:read",
    "product:manage",
    "inventory:read",
    "inventory:manage",
    "fixed_asset:read",
    "fixed_asset:manage",
    // Read-only: an accountant reconciles the payroll journal's GL impact
    // but payroll's own management/posting (and the TFN/bank-detail
    // sensitivity that comes with it) stays with PAYROLL_MANAGER/OWNER/
    // ADMINISTRATOR — see docs/security.md.
    "employee:read",
    "payrun:read",
    "budget:read",
    "budget:manage",
    "forecast:read",
    "forecast:manage",
    "scenario:read",
    "scenario:manage",
    "period:close",
    "period:reopen",
    "period:override_soft",
    "period:post_advisor_locked",
    "close_checklist:read",
    "close_checklist:manage",
  ]),
  BOOKKEEPER: new Set<Permission>([
    "account:read",
    "journal:read",
    "journal:post",
    "financial_report:read",
    "saved_report:manage",
    "contact:read",
    "contact:manage",
    "dimension:read",
    "dimension:manage",
    "bank_account:read",
    "bank_transaction:import",
    "bank_transaction:reconcile",
    "bank_rule:manage",
    "customer_invoice:read",
    "customer_invoice:manage",
    "customer_invoice:post",
    "customer_payment:read",
    "customer_payment:manage",
    "customer_quote:read",
    "customer_quote:manage",
    "recurring_invoice:read",
    "recurring_invoice:manage",
    "supplier_bill:read",
    "supplier_bill:manage",
    "supplier_bill:post",
    "supplier_payment:read",
    "supplier_payment:manage",
    "bank_transaction:ai_suggest",
    "expense_claim:read",
    "expense_claim:manage",
    "expense_claim:approve",
    "expense_receipt:manage",
    "purchase_order:read",
    "purchase_order:manage",
    "recurring_bill:read",
    "recurring_bill:manage",
    "supplier_credit:read",
    "supplier_credit:manage",
    "supplier_credit:post",
    "supplier_credit:void",
    "payment_run:read",
    "payment_run:manage",
    "payment_run:approve",
    "project:read",
    "project:manage",
    "timesheet:read",
    "timesheet:manage",
    "timesheet:approve",
    "product:read",
    "product:manage",
    "inventory:read",
    "inventory:manage",
    "fixed_asset:read",
    "fixed_asset:manage",
    "employee:read",
    "payrun:read",
    "budget:read",
    "budget:manage",
    "forecast:read",
    "forecast:manage",
    "scenario:read",
    "scenario:manage",
    // Sees the close checklist (it is how a bookkeeper learns what is still
    // outstanding) but cannot sign items off, close, or reopen.
    "close_checklist:read",
  ]),
  ACCOUNTS_RECEIVABLE: new Set<Permission>([
    "account:read",
    "journal:read",
    "contact:read",
    "contact:manage",
    "bank_account:read",
    "customer_invoice:read",
    "customer_invoice:manage",
    "customer_invoice:post",
    "customer_invoice:void",
    "customer_payment:read",
    "customer_payment:manage",
    "customer_quote:read",
    "customer_quote:manage",
    "recurring_invoice:read",
    "recurring_invoice:manage",
    "expense_claim:read",
    "expense_claim:manage",
    "expense_receipt:manage",
    "project:read",
    "project:manage",
    "timesheet:read",
    "product:read",
    "inventory:read",
  ]),
  ACCOUNTS_PAYABLE: new Set<Permission>([
    "account:read",
    "journal:read",
    "contact:read",
    "contact:manage",
    "bank_account:read",
    "supplier_bill:read",
    "supplier_bill:manage",
    "supplier_bill:post",
    "supplier_bill:void",
    "supplier_payment:read",
    "supplier_payment:manage",
    "expense_claim:read",
    "expense_claim:manage",
    "expense_receipt:manage",
    "purchase_order:read",
    "purchase_order:manage",
    "recurring_bill:read",
    "recurring_bill:manage",
    "supplier_credit:read",
    "supplier_credit:manage",
    "supplier_credit:post",
    "supplier_credit:void",
    "payment_run:read",
    "payment_run:manage",
    "payment_run:approve",
    "project:read",
    "product:read",
    "product:manage",
    "inventory:read",
    "inventory:manage",
    "fixed_asset:read",
    "fixed_asset:manage",
  ]),
  PAYROLL_MANAGER: new Set<Permission>([
    "account:read",
    "journal:read",
    "contact:read",
    "expense_claim:read",
    "expense_claim:manage",
    "expense_claim:approve",
    "expense_receipt:manage",
    "project:read",
    "timesheet:read",
    "timesheet:approve",
    // Phase 8 Slice 1: the full set of real permissions this role existed
    // as a placeholder for since Phase 1 — employee records (including
    // the sensitive TFN/bank fields, masked per `EmployeeService`'s doc
    // comment for anyone without employee:manage) and the on-demand pay
    // run lifecycle (create/review DRAFT, then post).
    "employee:read",
    "employee:manage",
    "payrun:read",
    "payrun:manage",
    "payrun:post",
  ]),
  MANAGER: new Set<Permission>([
    "account:read",
    "journal:read",
    "financial_report:read",
    "saved_report:manage",
    "dimension:read",
    "contact:read",
    "audit:read",
    "bank_account:read",
    "customer_invoice:read",
    "customer_payment:read",
    "customer_quote:read",
    "recurring_invoice:read",
    "supplier_bill:read",
    "supplier_payment:read",
    "purchase_order:read",
    "recurring_bill:read",
    "supplier_credit:read",
    "payment_run:read",
    "expense_claim:read",
    "expense_claim:manage",
    "expense_claim:approve",
    "expense_receipt:manage",
    "project:read",
    "project:manage",
    "timesheet:read",
    "timesheet:manage",
    "timesheet:approve",
    "product:read",
    "inventory:read",
    "fixed_asset:read",
    "budget:read",
    "forecast:read",
    "scenario:read",
    "close_checklist:read",
  ]),
  EMPLOYEE: new Set<Permission>([
    "expense_claim:read",
    "expense_claim:manage",
    "expense_receipt:manage",
    "project:read",
    "timesheet:read",
    "timesheet:manage",
  ]),
  READ_ONLY: new Set<Permission>([
    "account:read",
    "journal:read",
    "financial_report:read",
    "dimension:read",
    "contact:read",
    "audit:read",
    "bank_account:read",
    "customer_invoice:read",
    "customer_payment:read",
    "customer_quote:read",
    "recurring_invoice:read",
    "supplier_bill:read",
    "supplier_payment:read",
    "purchase_order:read",
    "recurring_bill:read",
    "supplier_credit:read",
    "payment_run:read",
    "expense_claim:read",
    "project:read",
    "timesheet:read",
    "product:read",
    "inventory:read",
    "fixed_asset:read",
    "budget:read",
    "forecast:read",
    "scenario:read",
    "close_checklist:read",
  ]),
};

export function roleHasPermission(role: MembershipRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role].has(permission);
}
