import type { membershipRoleEnum } from "@/db/schema";

/** Mirrors the `membership_role` Postgres enum in src/db/schema.ts. */
export type MembershipRole = (typeof membershipRoleEnum.enumValues)[number];

export const PERMISSIONS = [
  "organization:manage",
  "membership:manage",
  "account:read",
  "account:manage",
  "fiscal_period:manage",
  "journal:read",
  "journal:post",
  "journal:reverse",
  "contact:read",
  "contact:manage",
  "tax_code:manage",
  "dimension:manage",
  "audit:read",
  "bank_account:read",
  "bank_account:manage",
  "bank_transaction:import",
  "bank_transaction:reconcile",
  "bank_rule:manage",
  "customer_invoice:read",
  "customer_invoice:manage",
  "customer_invoice:post",
  "customer_invoice:void",
  "customer_payment:read",
  "customer_payment:manage",
  "customer_quote:read",
  "customer_quote:manage",
  "recurring_invoice:read",
  "recurring_invoice:manage",
  "supplier_bill:read",
  "supplier_bill:manage",
  "supplier_bill:post",
  "supplier_bill:void",
  "supplier_payment:read",
  "supplier_payment:manage",
  "onboarding:manage",
  "bank_transaction:ai_suggest",
  "expense_claim:read",
  "expense_claim:manage",
  "expense_claim:approve",
  "expense_receipt:manage",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

const ALL_PERMISSIONS = new Set<Permission>(PERMISSIONS);

/**
 * Static role → permission matrix for Phase 1. Later phases may extend this
 * with per-organization overrides (master spec §46's "attribute-level
 * policy enforcement"); a static matrix is the right amount of complexity
 * while the only permission-checked resources are the ledger, contacts, and
 * membership management.
 */
export const ROLE_PERMISSIONS: Record<MembershipRole, ReadonlySet<Permission>> = {
  OWNER: ALL_PERMISSIONS,
  ADMINISTRATOR: ALL_PERMISSIONS,
  ACCOUNTANT: new Set<Permission>([
    "account:read",
    "account:manage",
    "fiscal_period:manage",
    "journal:read",
    "journal:post",
    "journal:reverse",
    "contact:read",
    "contact:manage",
    "tax_code:manage",
    "dimension:manage",
    "audit:read",
    "bank_account:read",
    "bank_account:manage",
    "bank_transaction:import",
    "bank_transaction:reconcile",
    "bank_rule:manage",
    "customer_invoice:read",
    "customer_invoice:manage",
    "customer_invoice:post",
    "customer_invoice:void",
    "customer_payment:read",
    "customer_payment:manage",
    "customer_quote:read",
    "customer_quote:manage",
    "recurring_invoice:read",
    "recurring_invoice:manage",
    "supplier_bill:read",
    "supplier_bill:manage",
    "supplier_bill:post",
    "supplier_bill:void",
    "supplier_payment:read",
    "supplier_payment:manage",
    "bank_transaction:ai_suggest",
    "expense_claim:read",
    "expense_claim:manage",
    "expense_claim:approve",
    "expense_receipt:manage",
  ]),
  BOOKKEEPER: new Set<Permission>([
    "account:read",
    "journal:read",
    "journal:post",
    "contact:read",
    "contact:manage",
    "dimension:manage",
    "bank_account:read",
    "bank_transaction:import",
    "bank_transaction:reconcile",
    "bank_rule:manage",
    "customer_invoice:read",
    "customer_invoice:manage",
    "customer_invoice:post",
    "customer_payment:read",
    "customer_payment:manage",
    "customer_quote:read",
    "customer_quote:manage",
    "recurring_invoice:read",
    "recurring_invoice:manage",
    "supplier_bill:read",
    "supplier_bill:manage",
    "supplier_bill:post",
    "supplier_payment:read",
    "supplier_payment:manage",
    "bank_transaction:ai_suggest",
    "expense_claim:read",
    "expense_claim:manage",
    "expense_claim:approve",
    "expense_receipt:manage",
  ]),
  ACCOUNTS_RECEIVABLE: new Set<Permission>([
    "account:read",
    "journal:read",
    "contact:read",
    "contact:manage",
    "bank_account:read",
    "customer_invoice:read",
    "customer_invoice:manage",
    "customer_invoice:post",
    "customer_invoice:void",
    "customer_payment:read",
    "customer_payment:manage",
    "customer_quote:read",
    "customer_quote:manage",
    "recurring_invoice:read",
    "recurring_invoice:manage",
    "expense_claim:read",
    "expense_claim:manage",
    "expense_receipt:manage",
  ]),
  ACCOUNTS_PAYABLE: new Set<Permission>([
    "account:read",
    "journal:read",
    "contact:read",
    "contact:manage",
    "bank_account:read",
    "supplier_bill:read",
    "supplier_bill:manage",
    "supplier_bill:post",
    "supplier_bill:void",
    "supplier_payment:read",
    "supplier_payment:manage",
    "expense_claim:read",
    "expense_claim:manage",
    "expense_receipt:manage",
  ]),
  PAYROLL_MANAGER: new Set<Permission>([
    "account:read",
    "journal:read",
    "contact:read",
    "expense_claim:read",
    "expense_claim:manage",
    "expense_claim:approve",
    "expense_receipt:manage",
  ]),
  MANAGER: new Set<Permission>([
    "account:read",
    "journal:read",
    "contact:read",
    "audit:read",
    "bank_account:read",
    "customer_invoice:read",
    "customer_payment:read",
    "customer_quote:read",
    "recurring_invoice:read",
    "supplier_bill:read",
    "supplier_payment:read",
    "expense_claim:read",
    "expense_claim:manage",
    "expense_claim:approve",
    "expense_receipt:manage",
  ]),
  EMPLOYEE: new Set<Permission>(["expense_claim:read", "expense_claim:manage", "expense_receipt:manage"]),
  READ_ONLY: new Set<Permission>([
    "account:read",
    "journal:read",
    "contact:read",
    "audit:read",
    "bank_account:read",
    "customer_invoice:read",
    "customer_payment:read",
    "customer_quote:read",
    "recurring_invoice:read",
    "supplier_bill:read",
    "supplier_payment:read",
    "expense_claim:read",
  ]),
};

export function roleHasPermission(role: MembershipRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role].has(permission);
}
