import type { membershipRoleEnum } from "@/db/schema";

/** Mirrors the `membership_role` Postgres enum in src/db/schema.ts. */
export type MembershipRole = (typeof membershipRoleEnum.enumValues)[number];

export const PERMISSIONS = [
  "organization:manage",
  "membership:manage",
  "account:read",
  "account:manage",
  "fiscal_period:manage",
  "journal:read",
  "journal:post",
  "journal:reverse",
  "contact:read",
  "contact:manage",
  "tax_code:manage",
  "dimension:read",
  "dimension:manage",
  "audit:read",
  "bank_account:read",
  "bank_account:manage",
  "bank_transaction:import",
  "bank_transaction:reconcile",
  "bank_rule:manage",
  "customer_invoice:read",
  "customer_invoice:manage",
  "customer_invoice:post",
  "customer_invoice:void",
  "customer_payment:read",
  "customer_payment:manage",
  "customer_quote:read",
  "customer_quote:manage",
  "recurring_invoice:read",
  "recurring_invoice:manage",
  "supplier_bill:read",
  "supplier_bill:manage",
  "supplier_bill:post",
  "supplier_bill:void",
  "supplier_payment:read",
  "supplier_payment:manage",
  "onboarding:manage",
  "bank_transaction:ai_suggest",
  "expense_claim:read",
  "expense_claim:manage",
  "expense_claim:approve",
  "expense_receipt:manage",
  "purchase_order:read",
  "purchase_order:manage",
  "recurring_bill:read",
  "recurring_bill:manage",
  "supplier_credit:read",
  "supplier_credit:manage",
  "supplier_credit:post",
  "supplier_credit:void",
  "payment_run:read",
  "payment_run:manage",
  "payment_run:approve",
  "financial_report:read",
  "saved_report:manage",
  "project:read",
  "project:manage",
  "timesheet:read",
  "timesheet:manage",
  "timesheet:approve",
  "product:read",
  "product:manage",
  "inventory:read",
  "inventory:manage",
  "fixed_asset:read",
  "fixed_asset:manage",
  "employee:read",
  "employee:manage",
  "payrun:read",
  "payrun:manage",
  "payrun:post",
  // Phase 8 Slice 2 (BAS / GST preparation). `bas:read` views prepared statements, drill-downs and the CSV;
  // `bas:manage` prepares/discards DRAFTs; `bas:finalise` snapshots a BAS immutably and records a lodgement made
  // OUTSIDE Money Matters (human-only, never reachable by AI/API/automation actors).
  "bas:read",
  "bas:manage",
  "bas:finalise",
  // Phase 8 Slice 3 (payroll operations). `payslip:read` lets any member read THEIR OWN payslips (the service matches
  // the linked employee record's user id; only `employee:manage` holders see anyone else's). `leave:request` files
  // leave for oneself, `leave:read` sees everyone's requests, `leave:approve` decides them (never one's own).
  // `payroll_payment:manage` records net-wage settlements and super/PAYG remittances and generates the ABA file;
  // `payrun:reverse` reverses a posted pay run.
  "payslip:read",
  "leave:request",
  "leave:read",
  "leave:approve",
  "payroll_payment:read",
  "payroll_payment:manage",
  "payrun:reverse",
  "budget:read",
  "budget:manage",
  "forecast:read",
  "forecast:manage",
  "scenario:read",
  "scenario:manage",
  // Phase 9 Slice 3 (month-end close + period locking, master spec §40/§41).
  // `period:close` raises a period's lock level (and closes it);
  // `period:reopen` lowers a SOFT/ADVISOR lock; `period:reopen_hard` is the
  // most restricted — only it can lower a TAX_LOCKED/HARD_LOCKED period.
  // `period:override_soft` lets a holder post into a SOFT_LOCKED period with
  // an audited reason; `period:post_advisor_locked` lets the accountant keep
  // posting adjustments into an ADVISOR_LOCKED one. None of these is
  // reachable by any AI path (fiscal period close is a permanently
  // human-gated critical action — docs/ai-agents.md).
  "period:close",
  "period:reopen",
  "period:reopen_hard",
  "period:override_soft",
  "period:post_advisor_locked",
  "close_checklist:read",
  "close_checklist:manage",
  // Phase 9 Slice 4 (multi-entity consolidation, master spec §30).
  // `consolidation:manage` is checked IN THE ENTITY BEING ACTED ON — it is what
  // lets a user add that organization to a consolidation group, map its
  // accounts to the group chart, and designate intercompany accounts. Reading
  // a consolidated report needs no new permission: each entity's own
  // `financial_report:read` is checked per entity, with the user's real role
  // there, and an entity without it is excluded from the result.
  "consolidation:manage",
  // Phase 9 Slice 5 (accountant practice, master spec s.42). Queries and
  // document requests from the client's accountant are visible to the client:
  // `client_request:read` opens the inbox, `client_request:respond` replies
  // (and attaches a document), `client_request:manage` raises and closes a
  // request (held by the accountant-type roles a practice's staff are given in
  // a client). Linking a practice to the organization is `organization:manage`
  // (OWNER / ADMINISTRATOR only) — there is deliberately no weaker route.
  "client_request:read",
  "client_request:respond",
  "client_request:manage",
  // Phase 10 Slice 1 (public developer API, master spec s.54). Creating and
  // revoking API keys is held ONLY by OWNER / ADMINISTRATOR (they receive every
  // permission; no other role lists it). An API key can itself never carry this
  // permission - it is not reachable from any API scope (src/domain/api/scopes.ts).
  "api_key:manage",
  // Phase 10 Slice 2 (webhooks, master spec s.55). Managing webhook subscriptions (create, pause, rotate the
  // signing secret, replay) is held ONLY by OWNER / ADMINISTRATOR AND requires a HUMAN actor; like api_key:manage it
  // is not reachable from any API scope or AI tool.
  "webhook:manage",
  // Phase 10 Slice 3 (Automation Centre + integration framework, master spec s.75 / s.53). Creating, enabling, editing
  // and deleting an automation rule - and the org-wide "pause all" switch - is `automation:manage`: OWNER /
  // ADMINISTRATOR only AND a HUMAN actor (an API key, AI agent or automation can never hold it). Creating or enabling a
  // rule IS the human's explicit approval of that narrow action. `automation:read` lets other roles SEE the rules and
  // the run log. `integration:manage` (connect / test / disconnect a provider) is likewise OWNER / ADMINISTRATOR +
  // human only and is not reachable from any API scope, AI tool or automation action.
  "automation:read",
  "automation:manage",
  "integration:manage",
  // Phase 10 Slice 4 (OAuth 2.0 for third-party apps, master spec s.54). Registering, editing, disabling and deleting an
  // OAuth application, rotating its secret and revoking any of its grants is `oauth_app:manage`: OWNER / ADMINISTRATOR
  // only AND a HUMAN actor (an API key, an OAuth token, an AI agent or an automation can never hold it). Any member can
  // revoke THEIR OWN grants (that is not a permission: it is the right to withdraw your own consent).
  "oauth_app:manage",
  // Approval engine (master spec s.45). `approval:manage` configures approval policies and lets an owner/administrator reassign
  // a waiting step or override a request WITH a reason (always audited). OWNER / ADMINISTRATOR only AND a HUMAN actor: an API
  // key, OAuth token, AI agent or automation can never hold it, and can never decide an approval either (the approval
  // service refuses every non-HUMAN actor even when the role behind it is OWNER). Deciding a step is NOT a permission of
  // its own: it needs the policy-named role/user plus the document's own approve permission, recomputed at decision time.
  "approval:manage",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

const ALL_PERMISSIONS = new Set<Permission>(PERMISSIONS);

/**
 * Static role → permission matrix for Phase 1. Later phases may extend this
 * with per-organization overrides (master spec §46's "attribute-level
 * policy enforcement"); a static matrix is the right amount of complexity
 * while the only permission-checked resources are the ledger, contacts, and
 * membership management.
 */
export const ROLE_PERMISSIONS: Record<MembershipRole, ReadonlySet<Permission>> = {
  OWNER: ALL_PERMISSIONS,
  ADMINISTRATOR: ALL_PERMISSIONS,
  ACCOUNTANT: new Set<Permission>([
    "account:read",
    "account:manage",
    "fiscal_period:manage",
    "journal:read",
    "journal:post",
    "journal:reverse",
    "financial_report:read",
    "saved_report:manage",
    "contact:read",
    "contact:manage",
    "tax_code:manage",
    "dimension:read",
    "dimension:manage",
    "audit:read",
    "bank_account:read",
    "bank_account:manage",
    "bank_transaction:import",
    "bank_transaction:reconcile",
    "bank_rule:manage",
    "customer_invoice:read",
    "customer_invoice:manage",
    "customer_invoice:post",
    "customer_invoice:void",
    "customer_payment:read",
    "customer_payment:manage",
    "customer_quote:read",
    "customer_quote:manage",
    "recurring_invoice:read",
    "recurring_invoice:manage",
    "supplier_bill:read",
    "supplier_bill:manage",
    "supplier_bill:post",
    "supplier_bill:void",
    "supplier_payment:read",
    "supplier_payment:manage",
    "bank_transaction:ai_suggest",
    "expense_claim:read",
    "expense_claim:manage",
    "expense_claim:approve",
    "expense_receipt:manage",
    "purchase_order:read",
    "purchase_order:manage",
    "recurring_bill:read",
    "recurring_bill:manage",
    "supplier_credit:read",
    "supplier_credit:manage",
    "supplier_credit:post",
    "supplier_credit:void",
    "payment_run:read",
    "payment_run:manage",
    "payment_run:approve",
    "project:read",
    "project:manage",
    "timesheet:read",
    "timesheet:manage",
    "timesheet:approve",
    "product:read",
    "product:manage",
    "inventory:read",
    "inventory:manage",
    "fixed_asset:read",
    "fixed_asset:manage",
    // Read-only: an accountant reconciles the payroll journal's GL impact
    // but payroll's own management/posting (and the TFN/bank-detail
    // sensitivity that comes with it) stays with PAYROLL_MANAGER/OWNER/
    // ADMINISTRATOR — see docs/security.md.
    "employee:read",
    "payrun:read",
    "bas:read",
    "bas:manage",
    "bas:finalise",
    "payslip:read",
    "leave:request",
    "leave:read",
    "payroll_payment:read",
    "payroll_payment:manage",
    "payrun:reverse",
    "budget:read",
    "budget:manage",
    "forecast:read",
    "forecast:manage",
    "scenario:read",
    "scenario:manage",
    "period:close",
    "period:reopen",
    "period:override_soft",
    "period:post_advisor_locked",
    "close_checklist:read",
    "close_checklist:manage",
    // Accountants routinely consolidate several clients' or entities' books.
    "consolidation:manage",
    "client_request:read",
    "client_request:respond",
    "client_request:manage",
    "automation:read",
  ]),
  BOOKKEEPER: new Set<Permission>([
    "account:read",
    "journal:read",
    "journal:post",
    "financial_report:read",
    "saved_report:manage",
    "contact:read",
    "contact:manage",
    "dimension:read",
    "dimension:manage",
    "bank_account:read",
    "bank_transaction:import",
    "bank_transaction:reconcile",
    "bank_rule:manage",
    "customer_invoice:read",
    "customer_invoice:manage",
    "customer_invoice:post",
    "customer_payment:read",
    "customer_payment:manage",
    "customer_quote:read",
    "customer_quote:manage",
    "recurring_invoice:read",
    "recurring_invoice:manage",
    "supplier_bill:read",
    "supplier_bill:manage",
    "supplier_bill:post",
    "supplier_payment:read",
    "supplier_payment:manage",
    "bank_transaction:ai_suggest",
    "expense_claim:read",
    "expense_claim:manage",
    "expense_claim:approve",
    "expense_receipt:manage",
    "purchase_order:read",
    "purchase_order:manage",
    "recurring_bill:read",
    "recurring_bill:manage",
    "supplier_credit:read",
    "supplier_credit:manage",
    "supplier_credit:post",
    "supplier_credit:void",
    "payment_run:read",
    "payment_run:manage",
    "payment_run:approve",
    "project:read",
    "project:manage",
    "timesheet:read",
    "timesheet:manage",
    "timesheet:approve",
    "product:read",
    "product:manage",
    "inventory:read",
    "inventory:manage",
    "fixed_asset:read",
    "fixed_asset:manage",
    "employee:read",
    "payrun:read",
    // A bookkeeper prepares a BAS draft for the accountant but cannot finalise it.
    "bas:read",
    "bas:manage",
    "payslip:read",
    "leave:request",
    "payroll_payment:read",
    "budget:read",
    "budget:manage",
    "forecast:read",
    "forecast:manage",
    "scenario:read",
    "scenario:manage",
    // Sees the close checklist (it is how a bookkeeper learns what is still
    // outstanding) but cannot sign items off, close, or reopen.
    "close_checklist:read",
    "client_request:read",
    "client_request:respond",
    "client_request:manage",
    "automation:read",
  ]),
  ACCOUNTS_RECEIVABLE: new Set<Permission>([
    "payslip:read",
    "leave:request",
    "account:read",
    "journal:read",
    "contact:read",
    "contact:manage",
    "bank_account:read",
    "customer_invoice:read",
    "customer_invoice:manage",
    "customer_invoice:post",
    "customer_invoice:void",
    "customer_payment:read",
    "customer_payment:manage",
    "customer_quote:read",
    "customer_quote:manage",
    "recurring_invoice:read",
    "recurring_invoice:manage",
    "expense_claim:read",
    "expense_claim:manage",
    "expense_receipt:manage",
    "project:read",
    "project:manage",
    "timesheet:read",
    "product:read",
    "inventory:read",
  ]),
  ACCOUNTS_PAYABLE: new Set<Permission>([
    "payslip:read",
    "leave:request",
    "account:read",
    "journal:read",
    "contact:read",
    "contact:manage",
    "bank_account:read",
    "supplier_bill:read",
    "supplier_bill:manage",
    "supplier_bill:post",
    "supplier_bill:void",
    "supplier_payment:read",
    "supplier_payment:manage",
    "expense_claim:read",
    "expense_claim:manage",
    "expense_receipt:manage",
    "purchase_order:read",
    "purchase_order:manage",
    "recurring_bill:read",
    "recurring_bill:manage",
    "supplier_credit:read",
    "supplier_credit:manage",
    "supplier_credit:post",
    "supplier_credit:void",
    "payment_run:read",
    "payment_run:manage",
    "payment_run:approve",
    "project:read",
    "product:read",
    "product:manage",
    "inventory:read",
    "inventory:manage",
    "fixed_asset:read",
    "fixed_asset:manage",
  ]),
  PAYROLL_MANAGER: new Set<Permission>([
    "account:read",
    "journal:read",
    "contact:read",
    "expense_claim:read",
    "expense_claim:manage",
    "expense_claim:approve",
    "expense_receipt:manage",
    "project:read",
    "timesheet:read",
    "timesheet:approve",
    // Phase 8 Slice 1: the full set of real permissions this role existed
    // as a placeholder for since Phase 1 — employee records (including
    // the sensitive TFN/bank fields, masked per `EmployeeService`'s doc
    // comment for anyone without employee:manage) and the on-demand pay
    // run lifecycle (create/review DRAFT, then post).
    "employee:read",
    "employee:manage",
    "payrun:read",
    "payrun:manage",
    "payrun:post",
    "payrun:reverse",
    "payslip:read",
    "leave:request",
    "leave:read",
    "leave:approve",
    "payroll_payment:read",
    "payroll_payment:manage",
  ]),
  MANAGER: new Set<Permission>([
    "payslip:read",
    "leave:request",
    "leave:read",
    "leave:approve",
    "account:read",
    "journal:read",
    "financial_report:read",
    "saved_report:manage",
    "dimension:read",
    "contact:read",
    "audit:read",
    "bank_account:read",
    "customer_invoice:read",
    "customer_payment:read",
    "customer_quote:read",
    "recurring_invoice:read",
    "supplier_bill:read",
    "supplier_payment:read",
    "purchase_order:read",
    "recurring_bill:read",
    "supplier_credit:read",
    "payment_run:read",
    "expense_claim:read",
    "expense_claim:manage",
    "expense_claim:approve",
    "expense_receipt:manage",
    "project:read",
    "project:manage",
    "timesheet:read",
    "timesheet:manage",
    "timesheet:approve",
    "product:read",
    "inventory:read",
    "fixed_asset:read",
    "budget:read",
    "forecast:read",
    "scenario:read",
    "close_checklist:read",
    "client_request:read",
    "automation:read",
  ]),
  EMPLOYEE: new Set<Permission>([
    "payslip:read",
    "leave:request",
    "expense_claim:read",
    "expense_claim:manage",
    "expense_receipt:manage",
    "project:read",
    "timesheet:read",
    "timesheet:manage",
  ]),
  READ_ONLY: new Set<Permission>([
    "payslip:read",
    "account:read",
    "journal:read",
    "financial_report:read",
    "dimension:read",
    "contact:read",
    "audit:read",
    "bank_account:read",
    "customer_invoice:read",
    "customer_payment:read",
    "customer_quote:read",
    "recurring_invoice:read",
    "supplier_bill:read",
    "supplier_payment:read",
    "purchase_order:read",
    "recurring_bill:read",
    "supplier_credit:read",
    "payment_run:read",
    "expense_claim:read",
    "project:read",
    "timesheet:read",
    "product:read",
    "inventory:read",
    "fixed_asset:read",
    "budget:read",
    "forecast:read",
    "scenario:read",
    "close_checklist:read",
    "automation:read",
  ]),
};

export function roleHasPermission(role: MembershipRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role].has(permission);
}
